### ISSUE TITLE
Missing license for tm-scoreboard

### ISSUE THREAD

**Issue by VodBox** [LocoMH/TaskmasterSuite#1]
Hey. Just wanting to let you know that while I don't mind at all that you used my scoreboard graphic code as a base for the graphic portion, you haven't included attribution in your license notice per the MIT license on my repo. Would appreciate that being there. 🙂

**Comment by LocoMH** [comment]
Hi there, really sorry! I added a few others, thought I had all, but missed you. Thanks for letting me know and sorry for the late response. I updated the license!
